[profiling]
logger = { level = "basic", stdout = false }

[autotune]
level = "balanced"
logger = { level = "minimal", stdout = false }

[compilation]
logger = { level = "basic", file = "cubecl.log", append = true }

